apiVersion: mcp.kagenti.com/v1alpha1
kind: MCPGatewayExtension
metadata:
  name: {{ .Values.gateway.name | quote }}
  namespace: mcp-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gateway.name | quote }}
    namespace: {{ .Values.gateway.namespace | quote }}
    sectionName: mcp
  publicHost: {{ .Values.gateway.publicHost | quote }}
  privateHost: {{ printf "%s-%s.%s.svc.cluster.local:%v" .Values.gateway.name .Values.gateway.gatewayClassName .Values.gateway.namespace .Values.gateway.port | quote }}
  backendPingIntervalSeconds: {{ .Values.mcpGatewayExtension.pollInterval }}
